### ISSUE TITLE
TypeError: linspace() missing 1 required positional arguments: "steps"

### ISSUE THREAD

**Issue by tiansiyuan** [swarmapytorch/book_DeepLearning_in_PyTorch_Source#9]
in 02_DL_meets_PyTorch)/初识PyTorch basics.ipynb

when I run 

x = torch.linspace(0, 100).type(torch.FloatTensor)

I get

TypeError: linspace() missing 1 required positional arguments: "steps"

PyTorch version is 1.13.0

**Comment by lrenc** [comment]
x = torch.linspace(0, 99, steps=100).type(torch.FloatTensor)

**Comment by tiansiyuan** [comment]
fixed.
